import type { CuratedSong } from '../curatedSongs';

export const otherSongs: CuratedSong[] = [
  {
    id: 'despacito',
    title: 'Despacito',
    artist: 'Luis Fonsi ft. Daddy Yankee',
    videoId: 'kJQP7kiw5Fk',
    language: 'es',
    languageName: 'Spanish',
    difficulty: 'Hard',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80',
    lyrics: [
      { startTime: 0, endTime: 5, text: '(Intro)', translation: '(Intro)' },
      { startTime: 5, endTime: 9, text: 'Sí, sabes que ya llevo un rato mirándote', translation: "Yes, you know that I've been looking at you for a while" },
      { startTime: 9, endTime: 13, text: 'Tengo que bailar contigo hoy', translation: 'I have to dance with you today' },
      { startTime: 13, endTime: 17, text: 'Vi que tu mirada ya estaba llamándome', translation: "I saw that your look was already calling me" },
      { startTime: 17, endTime: 21, text: 'Muéstrame el camino que yo voy', translation: "Show me the way that I'm going" },
      { startTime: 21, endTime: 25, text: 'Tú, tú eres el imán y yo soy el metal', translation: 'You, you are the magnet and I am the metal' },
      { startTime: 25, endTime: 29, text: 'Me voy acercando y voy armando el plan', translation: 'I am getting closer and making a plan' },
      { startTime: 29, endTime: 33, text: 'Solo con pensarlo se acelera el pulso', translation: 'Just thinking about it speeds up my pulse' },
      { startTime: 33, endTime: 37, text: 'Ya, ya me está gustando más de lo normal', translation: 'Now, I am already liking it more than normal' },
      { startTime: 37, endTime: 41, text: 'Todos mis sentidos van pidiendo más', translation: 'All my senses are asking for more' },
      { startTime: 41, endTime: 45, text: 'Esto hay que tomarlo sin ningún apuro', translation: 'This has to be taken without any rush' },
      { startTime: 45, endTime: 49, text: 'Despacito', translation: 'Slowly' },
      { startTime: 49, endTime: 53, text: 'Quiero respirar tu cuello despacito', translation: 'I want to breathe your neck slowly' },
      { startTime: 53, endTime: 57, text: 'Deja que te diga cosas al oído', translation: 'Let me tell you things in your ear' },
      { startTime: 57, endTime: 62, text: 'Para que te acuerdes si no estás conmigo', translation: "So that you remember if you are not with me" },
    ]
  },
  {
    id: 'derniere-danse',
    title: 'Dernière Danse',
    artist: 'Indila',
    videoId: 'K5KyiYEcPyw',
    language: 'fr',
    languageName: 'French',
    difficulty: 'Medium',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80',
    lyrics: [
      { startTime: 0, endTime: 2, text: '(Intro)', translation: '(Intro)' },
      { startTime: 2, endTime: 6, text: 'Oh ma douce souffrance', translation: 'Oh my sweet suffering' },
      { startTime: 6, endTime: 10, text: "Pourquoi s'acharner ? Tu recommences", translation: 'Why persist? You start again' },
      { startTime: 10, endTime: 14, text: "Je ne suis qu'un être sans importance", translation: 'I am only a person of no importance' },
      { startTime: 14, endTime: 18, text: 'Sans lui, je suis un peu "paro"', translation: 'Without him, I am a bit crazy' },
      { startTime: 18, endTime: 22, text: 'Je déambule seule dans le métro', translation: 'I wander alone in the subway' },
      { startTime: 22, endTime: 26, text: 'Une dernière danse', translation: 'One last dance' },
      { startTime: 26, endTime: 30, text: 'Pour oublier ma peine immense', translation: 'To forget my immense pain' },
      { startTime: 30, endTime: 34, text: "Je veux m'enfuir, que tout recommence", translation: 'I want to run away, for everything to start again' },
      { startTime: 34, endTime: 38, text: 'Oh ma douce souffrance', translation: 'Oh my sweet suffering' },
      { startTime: 38, endTime: 42, text: 'Dans le bruit et la fureur', translation: 'In the noise and the fury' },
      { startTime: 42, endTime: 46, text: "Je cours auprès de ma peur", translation: 'I run close to my fear' },
      { startTime: 46, endTime: 50, text: "Mon souci est-ce ma douleur ?", translation: 'My concern, is it my pain?' },
      { startTime: 50, endTime: 54, text: 'Et je danse, danse, danse, danse, danse, danse, danse', translation: 'And I dance, dance, dance, dance, dance, dance, dance' },
      { startTime: 54, endTime: 58, text: 'Dans ce bruit, je cours et je pars', translation: 'In this noise, I run and I leave' },
      { startTime: 58, endTime: 62, text: "C'est mon tour, la douleur s'en va", translation: 'It is my turn, the pain goes away' },
      { startTime: 62, endTime: 67, text: 'Et je danse, danse, danse, danse, danse, danse, danse', translation: 'And I dance, dance, dance, dance, dance, dance, dance' },
    ]
  },
  {
    id: 'je-veux',
    title: 'Je Veux',
    artist: 'Zaz',
    videoId: 'Tm88QAI8I5A',
    language: 'fr',
    languageName: 'French',
    difficulty: 'Easy',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=400&q=80',
    lyrics: [
      { startTime: 0, endTime: 10, text: '(Acoustic Guitar Intro)', translation: '(Acoustic Guitar Intro)' },
      { startTime: 10, endTime: 14, text: "Donnez-moi une suite au Ritz, je n'en veux pas !", translation: "Give me a suite at the Ritz, I don't want it!" },
      { startTime: 14, endTime: 18, text: "Des bijoux de chez Chanel, je n'en veux pas !", translation: "Jewelry from Chanel, I don't want it!" },
      { startTime: 18, endTime: 21, text: "Donnez-moi une limousine, j'en ferais quoi ?", translation: "Give me a limousine, what would I do with it?" },
      { startTime: 21, endTime: 25, text: "Offrez-moi du personnel, j'en ferais quoi ?", translation: "Offer me staff, what would I do with it?" },
      { startTime: 25, endTime: 28, text: "Un manoir à Neuchâtel, ce n'est pas pour moi", translation: "A manor in Neuchâtel, it's not for me" },
      { startTime: 28, endTime: 32, text: "Offrez-moi la Tour Eiffel, j'en ferais quoi ?", translation: "Offer me the Eiffel Tower, what would I do with it?" },
      { startTime: 32, endTime: 36, text: "Je veux de l'amour, de la joie, de la bonne humeur", translation: "I want love, joy, good humor" },
      { startTime: 36, endTime: 40, text: "Ce n'est pas votre argent qui fera mon bonheur", translation: "It's not your money that will make me happy" },
      { startTime: 40, endTime: 44, text: "Moi, je veux crever la main sur le cœur", translation: "I want to die with my hand on my heart" },
    ]
  },
  {
    id: '99-luftballons',
    title: '99 Luftballons',
    artist: 'Nena',
    videoId: 'Fpu5a0R83x4',
    language: 'de',
    languageName: 'German',
    difficulty: 'Easy',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&q=80',
    lyrics: [
      { startTime: 0, endTime: 24, text: '(Synthesizer Intro)', translation: '(Synthesizer Intro)' },
      { startTime: 24, endTime: 30, text: 'Hast du etwas Zeit für mich?', translation: 'Do you have some time for me?' },
      { startTime: 30, endTime: 35, text: 'Dann singe ich ein Lied für dich', translation: "Then I'll sing a song for you" },
      { startTime: 35, endTime: 40, text: 'Von neunundneunzig Luftballons', translation: 'Of ninety-nine balloons' },
      { startTime: 40, endTime: 45, text: 'Auf ihrem Weg zum Horizont', translation: 'On their way to the horizon' },
      { startTime: 45, endTime: 50, text: "Denkst du vielleicht g'rad an mich?", translation: "Maybe you're thinking of me right now?" },
      { startTime: 50, endTime: 55, text: 'Dann singe ich ein Lied für dich', translation: "Then I'll sing a song for you" },
      { startTime: 55, endTime: 60, text: 'Von neunundneunzig Luftballons', translation: 'Of ninety-nine balloons' },
      { startTime: 60, endTime: 66, text: 'Und dass so was von so was kommt', translation: 'And that something like this comes from something like that' },
      { startTime: 66, endTime: 71, text: 'Neunundneunzig Luftballons', translation: 'Ninety-nine balloons' },
      { startTime: 71, endTime: 76, text: 'Auf ihrem Weg zum Horizont', translation: 'On their way to the horizon' },
      { startTime: 76, endTime: 81, text: 'Hielt man für Ufos aus dem All', translation: 'Were thought to be UFOs from space' },
      { startTime: 81, endTime: 86, text: 'Darum schickte ein General', translation: 'So a general sent up' },
      { startTime: 86, endTime: 91, text: 'Eine Fliegerstaffel hinterher', translation: 'A fighter squadron after them' },
      { startTime: 91, endTime: 96, text: 'Alarm zu geben, wenn es so wär', translation: 'To give the alarm if that were the case' },
      { startTime: 96, endTime: 101, text: 'Dabei war da am Horizont', translation: 'Yet there on the horizon were' },
      { startTime: 101, endTime: 106, text: 'Nur neunundneunzig Luftballons', translation: 'Only ninety-nine balloons' }
    ]
  }
];
