// Invidious API Client with Dynamic CORS Instance Discovery and Failover

const FALLBACK_INVIDIOUS_INSTANCES = [
  'https://inv.thepixora.com',
  'https://yewtu.be',
  'https://invidious.io',
  'https://invidious.projectsegfau.lt',
  'https://inv.nadeko.net'
];

let discoveredInstances: string[] = [];
let activeInstanceIndex = 0;

/**
 * Dynamically fetches the list of active Invidious instances and filters for the ones
 * that support CORS and API access.
 */
export async function getHealthyInstances(): Promise<string[]> {
  if (discoveredInstances.length > 0) {
    return discoveredInstances;
  }

  try {
    const res = await fetch('https://api.invidious.io/instances.json');
    if (!res.ok) throw new Error(`Status ${res.status}`);
    const data = await res.json();
    
    const healthy = data
      .filter((item: any) => {
        const inst = item[1];
        return inst.type === 'https' && !inst.monitor?.down && inst.api && inst.cors;
      })
      .map((item: any) => item[1].uri)
      .filter(Boolean);

    if (healthy.length > 0) {
      discoveredInstances = healthy;
      console.log(`Discovered ${healthy.length} CORS-enabled Invidious instances.`);
      return discoveredInstances;
    }
  } catch (err) {
    console.warn('Failed to load dynamic Invidious instances list, using fallbacks:', err);
  }

  discoveredInstances = FALLBACK_INVIDIOUS_INSTANCES;
  return discoveredInstances;
}

export function rotateInstance(instancesList: string[]) {
  activeInstanceIndex = (activeInstanceIndex + 1) % instancesList.length;
}

export function getActiveInstanceIndex(): number {
  return activeInstanceIndex;
}

/**
 * Helper to fetch data with automatic failover rotation across healthy Invidious instances.
 */
export async function fetchFromInvidious(path: string): Promise<any> {
  const instances = await getHealthyInstances();
  let attempts = 0;
  
  while (attempts < instances.length) {
    const baseUri = instances[activeInstanceIndex];
    const url = `${baseUri}${path}`;
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 5000); // 5s timeout
      
      const response = await fetch(url, { signal: controller.signal });
      clearTimeout(timeoutId);

      if (response.ok) {
        const text = await response.text();
        if (text.trim().startsWith('{') || text.trim().startsWith('[')) {
          return JSON.parse(text);
        }
        console.warn(`Instance ${baseUri} returned non-JSON text.`);
      } else {
        console.warn(`Instance ${baseUri} responded with status ${response.status}`);
      }
    } catch (err) {
      console.warn(`Failed fetching from Invidious instance ${baseUri}:`, err);
    }
    
    rotateInstance(instances);
    attempts++;
  }
  
  throw new Error('All healthy Invidious API instances failed to respond.');
}

export interface PipedVideoResult {
  videoId: string;
  title: string;
  artist: string;
  thumbnailUrl: string;
  duration: number; // in seconds
  isPlaylist?: boolean;
  videoCount?: number;
}

export interface SubtitleTrack {
  url: string;
  code: string; // e.g. "es", "en"
  name: string; // e.g. "Spanish", "English"
  autoGenerated: boolean;
}

/**
 * Searches YouTube videos and playlists using Invidious API (CORS-friendly).
 */
export async function searchVideos(query: string): Promise<PipedVideoResult[]> {
  if (!query.trim()) return [];
  
  try {
    const data = await fetchFromInvidious(`/api/v1/search?q=${encodeURIComponent(query)}`);
    const results = Array.isArray(data) ? data : [];
    
    return results
      .filter((item: any) => item.type === 'video' || item.type === 'playlist')
      .map((item: any) => {
        if (item.type === 'playlist') {
          const playlistId = item.playlistId || '';
          return {
            videoId: `playlist:${playlistId}`,
            title: item.title || 'Unknown Playlist',
            artist: item.author || 'YouTube Playlist',
            thumbnailUrl: item.playlistThumbnail || (item.videos?.[0]?.videoId ? `https://img.youtube.com/vi/${item.videos[0].videoId}/hqdefault.jpg` : 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80'),
            duration: 0,
            isPlaylist: true,
            videoCount: item.videoCount || 0
          };
        } else {
          const videoId = item.videoId || '';
          return {
            videoId,
            title: item.title || 'Unknown Title',
            artist: item.author || 'Unknown Artist',
            thumbnailUrl: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
            duration: item.lengthSeconds || 0,
          };
        }
      });
  } catch (err) {
    console.error('Search failed:', err);
    return [];
  }
}

/**
 * Fetches dynamic search recommendations by querying other songs by the same artist.
 */
export async function getRecommendations(artist: string, currentVideoId: string, targetLanguageName?: string): Promise<PipedVideoResult[]> {
  if (!artist || artist === 'Unknown Artist' || artist === 'YouTube Uploader') return [];
  try {
    let searchQuery = `${artist} songs`;
    if (targetLanguageName && targetLanguageName !== 'Any') {
      searchQuery = `${artist} ${targetLanguageName} songs`;
    }
    const data = await fetchFromInvidious(`/api/v1/search?q=${encodeURIComponent(searchQuery)}&filter=videos`);
    let results = Array.isArray(data) ? data : [];
    
    // If we have fewer than 3 results and a target language filter is active, fetch popular songs in that language
    const hasEnoughResults = results.filter((item: any) => item.type === 'video' && item.videoId !== currentVideoId).length >= 3;
    if (targetLanguageName && targetLanguageName !== 'Any' && !hasEnoughResults) {
      console.log(`Fewer than 3 recommendations for ${artist} in ${targetLanguageName}. Fetching popular fallback songs.`);
      const fallbackQuery = `popular ${targetLanguageName} songs`;
      const fallbackData = await fetchFromInvidious(`/api/v1/search?q=${encodeURIComponent(fallbackQuery)}&filter=videos`);
      if (Array.isArray(fallbackData)) {
        results = [...results, ...fallbackData];
      }
    }

    const seen = new Set<string>();
    seen.add(currentVideoId);

    return results
      .filter((item: any) => {
        if (item.type !== 'video' || !item.videoId || seen.has(item.videoId)) {
          return false;
        }
        seen.add(item.videoId);
        return true;
      })
      .slice(0, 6)
      .map((item: any) => {
        const videoId = item.videoId || '';
        return {
          videoId,
          title: item.title || 'Unknown Title',
          artist: item.author || artist,
          thumbnailUrl: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
          duration: item.lengthSeconds || 0,
        };
      });
  } catch (err) {
    console.error('Failed to fetch recommendations:', err);
    return [];
  }
}

/**
 * Fetches recommendations using the YouTube Data API key.
 */
export async function getYoutubeRecommendations(artist: string, currentVideoId: string, apiKey: string, targetLanguageName?: string): Promise<PipedVideoResult[]> {
  if (!artist || artist === 'Unknown Artist' || artist === 'YouTube Uploader') return [];
  try {
    let searchQuery = `${artist} songs`;
    if (targetLanguageName && targetLanguageName !== 'Any') {
      searchQuery = `${artist} ${targetLanguageName} songs`;
    }
    const response = await fetch(
      `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(searchQuery)}&type=video&maxResults=8&key=${apiKey}`
    );
    if (!response.ok) throw new Error(`YouTube API returned status ${response.status}`);
    const data = await response.json();
    let items = data.items || [];
    
    // If we have fewer than 3 results and a target language filter is active, fetch popular songs in that language
    const filteredCount = items.filter((item: any) => item.id?.videoId && item.id.videoId !== currentVideoId).length;
    if (targetLanguageName && targetLanguageName !== 'Any' && filteredCount < 3) {
      console.log(`Fewer than 3 YouTube recommendations for ${artist} in ${targetLanguageName}. Fetching popular fallback songs.`);
      const fallbackQuery = `popular ${targetLanguageName} songs`;
      const fallbackResponse = await fetch(
        `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(fallbackQuery)}&type=video&maxResults=8&key=${apiKey}`
      );
      if (fallbackResponse.ok) {
        const fallbackData = await fallbackResponse.json();
        if (fallbackData.items) {
          items = [...items, ...fallbackData.items];
        }
      }
    }

    const seen = new Set<string>();
    seen.add(currentVideoId);

    return items
      .filter((item: any) => item.id?.videoId && !seen.has(item.id.videoId))
      .map((item: any) => {
        seen.add(item.id.videoId);
        return {
          videoId: item.id.videoId,
          title: item.snippet.title,
          artist: item.snippet.channelTitle || artist,
          thumbnailUrl: item.snippet.thumbnails?.high?.url || `https://img.youtube.com/vi/${item.id.videoId}/hqdefault.jpg`,
          duration: 0
        };
      })
      .slice(0, 6);
  } catch (err) {
    console.error('Failed to get YouTube recommendations:', err);
    return [];
  }
}

/**
 * Fetches subtitle tracks for a YouTube video using Invidious API.
 */
export async function fetchSubtitleTracks(videoId: string): Promise<SubtitleTrack[]> {
  if (!videoId) return [];
  
  try {
    const data = await fetchFromInvidious(`/api/v1/captions/${videoId}`);
    const captionsList = data.captions || [];
    
    const instances = await getHealthyInstances();
    const currentBaseUri = instances[activeInstanceIndex];

    return captionsList.map((sub: any) => {
      const url = sub.url.startsWith('http') ? sub.url : `${currentBaseUri}${sub.url}`;
      return {
        url,
        code: sub.languageCode || 'unknown',
        name: sub.label || 'Unknown Language',
        autoGenerated: false,
      };
    });
  } catch (err) {
    console.error(`Failed to fetch subtitle tracks for video ${videoId}:`, err);
    return [];
  }
}

/**
 * Fetches and parses subtitle content from a subtitle URL.
 */
export async function fetchSubtitleContent(url: string): Promise<string> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch subtitle content: ${response.statusText}`);
    }
    return await response.text();
  } catch (err) {
    console.error('Failed to fetch subtitle content:', err);
    return '';
  }
}
