// Invidious API Client with Dynamic CORS Instance Discovery and Failover

const FALLBACK_INVIDIOUS_INSTANCES = [
  'https://inv.thepixora.com',
  'https://yewtu.be',
  'https://invidious.io',
  'https://invidious.projectsegfau.lt',
  'https://inv.nadeko.net'
];

let discoveredInstances: string[] = [];
let activeInstanceIndex = 0;

/**
 * Dynamically fetches the list of active Invidious instances and filters for the ones
 * that support CORS and API access.
 */
export async function getHealthyInstances(): Promise<string[]> {
  if (discoveredInstances.length > 0) {
    return discoveredInstances;
  }

  try {
    const res = await fetch('https://api.invidious.io/instances.json');
    if (!res.ok) throw new Error(`Status ${res.status}`);
    const data = await res.json();
    
    const healthy = data
      .filter((item: any) => {
        const inst = item[1];
        return inst.type === 'https' && !inst.monitor?.down && inst.api && inst.cors;
      })
      .map((item: any) => item[1].uri)
      .filter(Boolean);

    if (healthy.length > 0) {
      discoveredInstances = healthy;
      console.log(`Discovered ${healthy.length} CORS-enabled Invidious instances.`);
      return discoveredInstances;
    }
  } catch (err) {
    console.warn('Failed to load dynamic Invidious instances list, using fallbacks:', err);
  }

  discoveredInstances = FALLBACK_INVIDIOUS_INSTANCES;
  return discoveredInstances;
}

export function rotateInstance(instancesList: string[]) {
  activeInstanceIndex = (activeInstanceIndex + 1) % instancesList.length;
}

export function getActiveInstanceIndex(): number {
  return activeInstanceIndex;
}

/**
 * Helper to fetch data with automatic failover rotation across healthy Invidious instances.
 */
export async function fetchFromInvidious(path: string): Promise<any> {
  const instances = await getHealthyInstances();
  let attempts = 0;
  
  while (attempts < instances.length) {
    const baseUri = instances[activeInstanceIndex];
    const url = `${baseUri}${path}`;
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 5000); // 5s timeout
      
      const response = await fetch(url, { signal: controller.signal });
      clearTimeout(timeoutId);

      if (response.ok) {
        const text = await response.text();
        if (text.trim().startsWith('{') || text.trim().startsWith('[')) {
          return JSON.parse(text);
        }
        console.warn(`Instance ${baseUri} returned non-JSON text.`);
      } else {
        console.warn(`Instance ${baseUri} responded with status ${response.status}`);
      }
    } catch (err) {
      console.warn(`Failed fetching from Invidious instance ${baseUri}:`, err);
    }
    
    rotateInstance(instances);
    attempts++;
  }
  
  throw new Error('All healthy Invidious API instances failed to respond.');
}

export interface PipedVideoResult {
  videoId: string;
  title: string;
  artist: string;
  thumbnailUrl: string;
  duration: number; // in seconds
}

export interface SubtitleTrack {
  url: string;
  code: string; // e.g. "es", "en"
  name: string; // e.g. "Spanish", "English"
  autoGenerated: boolean;
}

/**
 * Searches YouTube videos using Invidious API (CORS-friendly).
 */
export async function searchVideos(query: string): Promise<PipedVideoResult[]> {
  if (!query.trim()) return [];
  
  try {
    const data = await fetchFromInvidious(`/api/v1/search?q=${encodeURIComponent(query)}&filter=videos`);
    const results = Array.isArray(data) ? data : [];
    
    return results
      .filter((item: any) => item.type === 'video')
      .map((item: any) => {
        const videoId = item.videoId || '';
        return {
          videoId,
          title: item.title || 'Unknown Title',
          artist: item.author || 'Unknown Artist',
          thumbnailUrl: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
          duration: item.lengthSeconds || 0,
        };
      });
  } catch (err) {
    console.error('Search failed:', err);
    return [];
  }
}

/**
 * Fetches subtitle tracks for a YouTube video using Invidious API.
 */
export async function fetchSubtitleTracks(videoId: string): Promise<SubtitleTrack[]> {
  if (!videoId) return [];
  
  try {
    const data = await fetchFromInvidious(`/api/v1/captions/${videoId}`);
    const captionsList = data.captions || [];
    
    const instances = await getHealthyInstances();
    const currentBaseUri = instances[activeInstanceIndex];

    return captionsList.map((sub: any) => {
      const url = sub.url.startsWith('http') ? sub.url : `${currentBaseUri}${sub.url}`;
      return {
        url,
        code: sub.languageCode || 'unknown',
        name: sub.label || 'Unknown Language',
        autoGenerated: false,
      };
    });
  } catch (err) {
    console.error(`Failed to fetch subtitle tracks for video ${videoId}:`, err);
    return [];
  }
}

/**
 * Fetches and parses subtitle content from a subtitle URL.
 */
export async function fetchSubtitleContent(url: string): Promise<string> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch subtitle content: ${response.statusText}`);
    }
    return await response.text();
  } catch (err) {
    console.error('Failed to fetch subtitle content:', err);
    return '';
  }
}
